version: '3.7'

services:

  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn testcase.wsgi:application --bind 0.0.0.0:8000 #--worker-class gevent
    volumes:
      - static_volume:/home/testcase/web/testcase/static
    expose:
      - 8000
    env_file:
      ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/testcase/web/testcase/static
    ports: 
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: