# Generated by Django 3.0.7 on 2020-10-08 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_blog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='subscriber',
            field=models.ManyToManyField(blank=True, related_name='subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
