# Generated by Django 3.0.7 on 2020-10-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201008_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
